### ISSUE TITLE
Cannot find DelphiVCL.pyd

### ISSUE THREAD

**Issue by ahmedmohiduet** [Embarcadero/DelphiVCL4Python#36]
I am facing error while running sample `python3 hellodelphivcl.py`:

```
Traceback (most recent call last):
  File "hellodelphivcl.py", line 1, in <module>
    from delphivcl import *
  File "/home/mohi/.local/lib/python3.8/site-packages/delphivcl/__init__.py", line 22, in <module>
    package = new_import()
  File "/home/mohi/.local/lib/python3.8/site-packages/delphivcl/__init__.py", line 15, in new_import
    ld = loader.create_module(spec)
ImportError: /home/mohi/.local/lib/python3.8/site-packages/delphivcl/DelphiVCL.pyd: cannot open shared object file: No such file or directory
```
Any clues?

**Comment by lmbelo** [comment]
Which platform are you using? The VCL library only works on Windows. Try the FMX library instead.

**Comment by ahmedmohiduet** [comment]
Got it. I am running Ubuntu 20.04.
